### ISSUE TITLE
Can't get trigger filters to work with Actions

### ISSUE THREAD

**Issue by brcrista** [recorefx/RecoreFX#11]
Doc: https://help.github.com/en/articles/workflow-syntax-for-github-actions#on

I can't figure out the right way to set up this filtered trigger.  In all of these cases, the trigger just doesn't fire.

```yml
on:
  push:
    paths:
    - '!docs/*'
```

```yml
on:
  push:
    paths:
    - '*'
    - '!docs/*'
```

```yml
on:
  push:
    branch:
    - '*'
    paths:
    - '!docs/*'
```
